### PR TITLE
start adding 0.5 support

### PR DESCRIPTION
**Pull request by CarlKenner**
I started adding 0.5 support. It compiles and runs, but the actual implementation isn't there yet, so you don't see anything.

### CODE REVIEW

**Comment by CarlKenner** [comment]
It should be working now, at least for Oculus Room Tiny.
I haven't implemented the mirror window yet though, which means the mirror window is invisible. You need to focus the mirror window with Alt+Tab or by hovering over the taskbar button and clicking on the preview window that appears. Simply clicking on the taskbar button doesn't give the window focus.

**Comment by kalavaras** [comment]
nice! I'll review this in about 9 hours

**Comment by CarlKenner** [comment]
I just tested in Oculus World Demo 0.5.0.1 and it works (if you use the Release x86 version). The sRGB is wrong for Oculus World Demo, and the HUD is displayed with the parallax backwards, but I think I know how to fix those issues. And of course, the mirror window is still blank.

**Comment by kalavaras** [comment]
Yeah. I went through it now and you are doing a good job. Do you still want to continue within this pull request or should I merge this and you make a new one later?

**Comment by CarlKenner** [comment]
I'd merge it if I were you. I can make another pull request when I have done more.

**Comment by kalavaras** [comment]
Ok. Btw I tested Neos The Universe with this and it crashed (no suprise at this point). I got the following in the output_log.txt. It seems 0.5.0.1 has a different kind of response to ovr_GetVersionString()
[output_log.txt](https://github.com/kalavaras/LibOVRWrapper/files/266451/output_log.txt)

**Comment by CarlKenner** [comment]
I'll start up my old computer and see what the real 0.5 DLL says.

BTW, I hope I didn't interfere with anything you were doing. I just saw there wasn't any 0.5 support and I had a sudden urge to try to implement it.

**Comment by kalavaras** [comment]
Actually I was toying with starting doing this and was at the point where I copied the 0.5 files to the folder but all better that somebody else is doing it :)

**Comment by CarlKenner** [comment]
I hope I copied them the right way. 0.5 seems to need the kernel. And there was a single project for DX11 and OpenGL.

**Comment by kalavaras** [comment]
yeah. I had the exact same folders and project names.

**Comment by CarlKenner** [comment]
The hard part will be the mirror window, because I think we're supposed to call Present, but we don't seem to have the swapchain interface that the game uses, only the backbuffer render target, device, and HWND.

**Comment by kalavaras** [comment]
You would probably need to make some debug code with oculus room tiny or oculusworlddemo that call it directly at the right point to see if it is needed.

**Comment by CarlKenner** [comment]
I fixed the version number and submitted a new pull request.

**Pull request merged**
