### PR TITLE
Version string

### PR DESCRIPTION
**Pull request by CarlKenner**

### CODE REVIEW

**Comment by kalavaras** [comment]
The version error is no longer reported in the unity output log but it is still crashing with the same stack trace. It seems the version error was only a log message. I also added some trace logging in master. It seems it does not like something (a string) in the ovrHmdDesc structure that ovrHmd_Create returns.

> 00007FFA198DA35B (mono) mono_string_new
> 0000000003B41735 (Mono JIT Code) (wrapper managed-to-native) System.Runtime.InteropServices.Marshal:PtrToStringAnsi (intptr)
> 0000000003B43847 (Mono JIT Code) Ovr.HmdDesc:.ctor (Ovr.HmdDesc_Raw64)
> 0000000003B42E5A (Mono JIT Code) Ovr.Hmd:GetDesc ()
> 0000000003B425F3 (Mono JIT Code) OVRDisplay:ConfigureEyeDesc (OVREye)
> 0000000003B42037 (Mono JIT Code) OVRDisplay:.ctor ()
> 0000000003B4053D (Mono JIT Code) OVRManager:Awake ()

**Comment by kalavaras** [comment]
I need to stop for today on this. I'll catch on your progress tomorrow if you still do something.

**Comment by CarlKenner** [comment]
OK. Thanks.

**Comment by CarlKenner** [comment]
I fixed that crash. Now the game launches, the sound plays until the safety screen shows, the safety screen works until you press the button, but then the safety screen tells you to wait and then tells you the game is having trouble loading.

That is the same behaviour I got before in Oculus Room Tiny before I implemented rendering. I think it is waiting for the game (wrapper) to call ovr_SubmitFrame successfully.

**Pull request merged**
